version: "3"
services:
  weatherchain_bootnode:
    hostname: weatherchain_bootnode
    build:
      context: ./Docker
      dockerfile: ./bootnode/Dockerfile
    ports:
    - ${BOOTNODE_PORT}:${BOOTNODE_PORT}/udp
    environment:
    - BOOTNODE_PORT=${BOOTNODE_PORT}

  weatherchain_validator_1:
    hostname: weatherchain_validator_1
    depends_on:
    - weatherchain_bootnode
    environment:
    - PUBLIC_ADDRESS=${EV1_PUBLIC_ADDRESS}
    - BOOTNODE_ID=${BOOTNODE_ID}
    - BOOTNODE_IP=${BOOTNODE_IP}
    - BOOTNODE_PORT=${BOOTNODE_PORT}
    - WRKCHAIN_NETWORK_ID=${WRKCHAIN_NETWORK_ID}
    - GETH_LISTEN_PORT=${WRKCHAIN_EV1_GETH_LISTEN_PORT}
    build:
      context: ./Docker
      dockerfile: ./validator/Dockerfile
      args:
        PRIVATE_KEY: ${EV1_PRIVATE_KEY}
        WALLET_PASS: ${EV1_WALLET_PASS}
        GENESIS_JSON_FILENAME: ${WRKCHAIN_GENESIS_JSON_FILENAME}
    container_name: weatherchain_validator_1
    ports:
    - ${WRKCHAIN_EV1_GETH_LISTEN_PORT}:${WRKCHAIN_EV1_GETH_LISTEN_PORT}/udp

  weatherchain_validator_2:
    hostname: weatherchain_validator_2
    depends_on:
    - weatherchain_bootnode
    environment:
    - PUBLIC_ADDRESS=${EV2_PUBLIC_ADDRESS}
    - BOOTNODE_ID=${BOOTNODE_ID}
    - BOOTNODE_IP=${BOOTNODE_IP}
    - BOOTNODE_PORT=${BOOTNODE_PORT}
    - WRKCHAIN_NETWORK_ID=${WRKCHAIN_NETWORK_ID}
    - GETH_LISTEN_PORT=${WRKCHAIN_EV2_GETH_LISTEN_PORT}
    build:
      context: ./Docker
      dockerfile: ./validator/Dockerfile
      args:
        PRIVATE_KEY: ${EV2_PRIVATE_KEY}
        WALLET_PASS: ${EV2_WALLET_PASS}
        GENESIS_JSON_FILENAME: ${WRKCHAIN_GENESIS_JSON_FILENAME}
    container_name: weatherchain_validator_2
    ports:
    - ${WRKCHAIN_EV2_GETH_LISTEN_PORT}:${WRKCHAIN_EV2_GETH_LISTEN_PORT}/udp

  weatherchain_node_1:
    hostname: weatherchain_node_1
    depends_on:
    - weatherchain_validator_1
    environment:
    - BOOTNODE_ID=${BOOTNODE_ID}
    - BOOTNODE_IP=${BOOTNODE_IP}
    - BOOTNODE_PORT=${BOOTNODE_PORT}
    - WRKCHAIN_NETWORK_ID=${WRKCHAIN_NETWORK_ID}
    - GETH_LISTEN_PORT=${WRKCHAIN_RPC_NODE_GETH_LISTEN_PORT}
    - RPC_PORT=${WRKCHAIN_RPC_PORT}
    build:
      context: ./Docker
      dockerfile: ./node/Dockerfile
      args:
        PRIVATE_KEY: ${RPC_NODE_PRIVATE_KEY}
        WALLET_PASS: ${RPC_NODE_WALLET_PASS}
        GENESIS_JSON_FILENAME: ${WRKCHAIN_GENESIS_JSON_FILENAME}
    container_name: weatherchain_node_1
    ports:
    - ${WRKCHAIN_RPC_PORT}:${WRKCHAIN_RPC_PORT}

  weatherchain_explorer:
    hostname: weatherchain_explorer
    depends_on:
    - weatherchain_node_1
    ports:
    - ${WRKCHAIN_EXPLORER_PORT}:${WRKCHAIN_EXPLORER_PORT}
    environment:
    - WRKCHAIN_EXPLORER_PORT=${WRKCHAIN_EXPLORER_PORT}
    build:
      context: ./Docker
      dockerfile: ./explorer/Dockerfile
      args:
        WRKCHAIN_EXPLORER_PORT: ${WRKCHAIN_EXPLORER_PORT}
        WRKCHAIN_RPC_PORT: ${WRKCHAIN_RPC_PORT}
        COIN_SYM: ${WRKCHAIN_COIN_SYM}

    container_name: weatherchain_explorer

  weather_service:
    hostname: weather_service
    depends_on:
      - weatherchain_node_1
    build:
      context: ./Docker
      dockerfile: ./weather_service/Dockerfile
    ports:
    - ${WEATHERCHAIN_UI_PORT}:${WEATHERCHAIN_UI_PORT}
    container_name: weather_service

  weatherchain_oracle:
    hostname: weatherchain_oracle
    depends_on:
      - weather_service
    build:
      context: ./Docker
      dockerfile: ./wrkchain_oracle/Dockerfile
    container_name: weatherchain_oracle
    environment:
    - MAINCHAIN_WEB3_PROVIDER_URL=${MAINCHAIN_WEB3_PROVIDER_URL}
    - WRKCHAIN_WEB3_PROVIDER_URL=${WRKCHAIN_WEB3_PROVIDER_URL}
    - PRIVATE_KEY=${EV1_PRIVATE_KEY}
    - WRKCHAIN_ROOT_CONTRACT_ADDRESS=${WRKCHAIN_ROOT_CONTRACT_ADDRESS}
    - WRKCHAIN_ROOT_WRITE_TIMEOUT=${WRKCHAIN_ROOT_WRITE_TIMEOUT}
    - WRKCHAIN_NETWORK_ID=${WRKCHAIN_NETWORK_ID}

